---
# Make sure to encrypt this file using ansible-vault to protect sensitive information
# ansible-vault encrypt group_vars/all/vault.yml
# OpenShift Cluster login Credentials for token refresh
oc_username: "your_openshift_username"           # Replace with your OpenShift username
oc_password: "your_openshift_password"           # Replace with your OpenShift password
oc_api_url: "https://api.aa02-ocp.flexpodb4.cisco.com:6443"    # Replace with your OpenShift API URL
oc_kubeconfig_path: "kubeconfig.txt"                        # Path to the kubeconfig file